### ISSUE TITLE
Gathering ideas and defining the technology!!

### ISSUE THREAD

**Issue by rebecatschiedel** [Web-Dev-Path/web-dev-path#33]
Hello, wonderful web devs,

this is an issue to gather ideas for our project, how and what we want it to look like, and what would be the best technology to use in order to achieve our goals: [Gatsby](https://www.gatsbyjs.com/) or [NextJS](https://nextjs.org/).

Let's get creative!!

**Comment by MarianaSouza** [comment]
Thanks for creating this issue @rebecatschiedel !

I've been reading and watching some tutorials about Gastby and Next.js, both are nice React frameworks, and for now, I tend to think that using Next.js would make the app more scalable allowing us to add future features other than the simple blog and pages with card components we see on the example platform: https://www.samanthaming.com/

https://dev.to/jameesy/gatsby-vs-next-js-what-why-and-when-4al5#:~:text=JS%20is%20mainly%20a%20tool%20for%20server%2Dside%20rendered%20pages.&text=Gatsby%20just%20generates%20pure%20HTML,HTML%20page%20from%20the%20server.

As we talked about at our meeting, instead of having cards with code hints (which could be explored on a blog post as well), we could offer a space where developers or maybe even non-profits could share projects that need help.

**Comment by ZahraB21** [comment]
I love the idea of having a place where other developers can share their projects and seek help. 

In regards to Next.js vs Gatsby, both are great frameworks. As @MarianaSouza cited, Next.js is more scalable but Gatsby is mostly used for static pages. Also, Gatsby can used with headless CMS as well. Would we be using CMS later on through the site? So, maybe that can be something we can think of.

As for me, I respect your decisions and would be happy to work with any of the frameworks. :)

**Comment by MarianaSouza** [comment]
Hey @ZahraB21  :D

Thanks for sharing your thoughts! <3
Yes, I guess having a CMS is ideal because we want to able to have a blog too. Both are nice frameworks for sure and that's exactly why is so hard to pick one, haha. If you're all OK with that, I think we should start giving a go with Next.js first. In case we realize it's not the perfect solution for us in the way, we can always start over with Gatsby. Let me know your thoughts! ;)

**Comment by rebecatschiedel** [comment]
Hi @MarianaSouza and @ZahraB21, 

Both frameworks are new for me, but I agree with you that Next.js looks a better fit for our project for now.
Do you think it would be a good idea to create a place where we can share the resources we are using to study it?

**Comment by MarianaSouza** [comment]
> Hi @MarianaSouza and @ZahraB21,
> 
> Both frameworks are new for me, but I agree with you that Next.js looks a better fit for our project for now.
> Do you think it would be a good idea to create a place where we can share the resources we are using to study it?

I think we can share those resources here on this issue, @rebecatschiedel . You can just drop the list with the links you're consulting to get ready for Next.js implementation, for example.

**Comment by rebecatschiedel** [comment]
For those who never had any contact with NextJS before, this was a helpful video:
[NextJs in 100 seconds + Full Beginners Tutorial - Fireship](https://www.youtube.com/watch?v=Sklc_fQBmcs).

These are the recommended reading by @MarianaSouza:
[Routing Introduction](https://nextjs.org/docs/routing/introduction)
[Dynamic Routes](https://nextjs.org/docs/routing/dynamic-routes)
[Dynamic Routes Segments](https://nextjs.org/docs/routing/introduction#dynamic-route-segments)
[API reference - router userouter](https://nextjs.org/docs/api-reference/next/router#userouter)
[Deployment](https://nextjs.org/docs/deployment)
