### ISSUE TITLE
CMS (blogging) Research

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#85]
We need to research and report findings related to a CMS (blogging) implementation for our project.

CMS requirements:
* Integrates with Next.js in the most straightforward way.
* Easy UI so anyone, not just a developer, could access it and add the article with support for images, links, and videos.
* An affordable solution, preferably with an initial free version so we can test it out beforehand.

Please report your findings in the comments or in a Google Stylesheet doc that can be shared here.

**Comment by vmcodes** [comment]
### Here is a list of Headless CMS options that I think would be viable for Web Dev Path. 
I personally believe that Contentful is the best option because I don't think it will require the paid option and is easy to configure. Please feel free to contribute any opinions or options you think should be considered. :rocket:

## Contentful 

**Benefits** 
- Founded in 2013, proven track record and reliable CDN.
- Generous free plan. 
- Integrates with Next JS. 
- Localization options, one additional language included for free. 
- Easy to use UI for developers and content writers. 

**Drawbacks** 
- Expensive if needs go beyond free plan. 
- A max of 5 user accounts for free option. 
- Only 2 role types (Admin and Editor) 

## Strapi 

**Benefits** 
- Completely Open Source and unlimited free use. 
- Coded in JavaScript and fully customizable. 
- Extensive documentation with different hosting options. 
- Integrates with Next JS. 
- Several localization options. 

**Drawbacks** 
- Requires configuring and installation for self hosting. 
- Potential costs for self hosting. 
- Requires plugins for certain functionalities. 

## Sanity 

**Benefits** 
- Free plan with the cheapest paid option. 
- Integrates with Next JS. 
- Currently supports large companies, proven track record. 
- Can host via frontend React only. 
- Free CDN for assets. 

**Drawbacks** 
- Requires plugin installation. 
- Most limited free plan. 
- More difficult integration.

**Comment by mariana-caldas** [comment]
I've heard wonderful things about Sanity, @vmcodes , thanks for adding that to your Discovery/Research! Let's dig into those options and share these initial thoughts with the group! 🚀

**Comment by mariana-caldas** [comment]
> > I've heard wonderful things about Sanity, @vmcodes , thanks for adding that to your Discovery/Research! Let's dig into those options and share these initial thoughts with the group! 🚀
> 
> @mariana-caldas I found an [example blog](https://www.sanity.io/create?template=sanity-io%2Fsanity-template-nextjs-blog-comments) from Sanity. Let me know your thoughts, I could try a test deploy if you'd like to take a look at a live version.

That would be great @vmcodes ! The only thing is that we're using Netlify and not Vercel in this project.

**Comment by Faith-Nchifor** [comment]
I'm really excited about using Contentful. Apart from being popular it seems very easy to start with.

**Comment by mariana-caldas** [comment]
> I'm really excited about using Contentful. Apart from being popular it seems very easy to start with.

Now you mention that, @Faith-Nchifor , I'll take it a second look. Thanks!  👀 🎉

**Comment by cherylli** [comment]
strapi ( if they do a free tier, strapi cloud coming soon -(https://strapi.io/pricing-cloud)  or sanity might a better option since we can self host 

We would be fine with any free tier for a while, but if we ever need to scale up, not being able to self host means we are stuck with the paid tier.

With self hosting, you can basically get a VPS with reasonable spec for $30 / year.  

There's also keystone.js 
https://github.com/keystonejs/keystone
https://jamstack.org/headless-cms/keystone/

**Comment by Denise-Carlson** [comment]
When [Ghost](https://ghost.org/) first launched in 2013, the main goal was to be a strict [blogging platform](https://kinsta.com/learn/blogging-tips/) that was easy to use. But since then, it’s developed into a sleek, 100% [headless Node.JS CMS](https://kinsta.com/blog/cms-software/#21-ghost--free-from-29month-hosted-version).

It has built-in advanced SEO options and a sleek web app dashboard that is powered by JavaScript.

Features
Sleek Markdown Editor.
Password Protection.
Global Navigation.
Multi-User Environment.
Content Scheduling.
SEO-Friendly Content Structure.
Advanced SEO Options.
Interface and Ease of Use
As far as ease of use goes, installing Ghost can be a little bit complicated since it’s not offered as a one-click installation option. But once it’s installed, the Ghost dashboard is simple, sleek, and easier to use.

ghost interface
Ghost interface
New installations are automatically populated with content that is essentially a tutorial on how to use Ghost.

Like [WordPress’ Gutenberg editor](https://kinsta.com/blog/gutenberg-wordpress-editor/), the Ghost editor is truly on-page WYSIWYG. It feels like you are writing and editing a live page on the site, but you can only add images, links, quotes, and format your text with markdown.

Ghost editor
Ghost’s dynamic menu
Since the entire dashboard, not just the editor like with WordPress, is based on JavaScript, the user experience is exceptionally smooth. It’s a one-page web app and acts like one. You never have to load a new admin page or wait for a page to refresh.

Pricing
The self-hosted version is open source and free. The hosted pro version [starts at $29 per month](https://ghost.org/pricing/).

**Comment by vmcodes** [comment]
Another option I've recently become a bit of a fan of is the MDX blog approach.
[Create a Next.js and MDX blog](https://blog.logrocket.com/create-next-js-mdx-blog/)

**Comment by cherylli** [comment]
This is another option - no hosting required. We blog on hashnode and display on our website through hashnode API. It was super easy to write on hashnode, 
Team account is also available
https://catalins.tech/hashnode-api-how-to-display-your-blog-articles-on-your-portfolio-page

**Comment by vmcodes** [comment]
> This is another option - no hosting required. We blog on hashnode and display on our website through hashnode API. It was super easy to write on hashnode, Team account is also available https://catalins.tech/hashnode-api-how-to-display-your-blog-articles-on-your-portfolio-page

That sounds cool. I'm a fan of GraphQL and have never used it with Next.js

**Comment by mariana-caldas** [comment]
> This is another option - no hosting required. We blog on hashnode and display on our website through hashnode API. It was super easy to write on hashnode, Team account is also available https://catalins.tech/hashnode-api-how-to-display-your-blog-articles-on-your-portfolio-page

This indeed sounds cool and relatively simple @cherylli and @vmcodes !

My concerns here are:
* Since we're grabbing the articles from one single account, how would we manage access to that account
* Could we style those single posts somehow or we would have to stick with hashnode platform? In case we can't style those pages, how do you feel about that?

**Comment by cherylli** [comment]
hashnode has organization accounts, so you could create one and invite people to join it
yes you can style it, it would just be pulling data like titles, content, etc 
not sure about tags, I can have a look

**Comment by cherylli** [comment]
I found out hashnode api does not support teams so I looked at dev.to it seems it has all the features we wanted,
- oranisation,
- api
- search by tags using query parameters

**Comment by mariana-caldas** [comment]
> I found out hashnode api does not support teams so I looked at dev.to it seems it has all the features we wanted,
> 
> * oranisation,
> * api
> * search by tags using query parameters

Love it, @cherylli ! I've created an organization to test it. It seems I just need to invite people by giving them a code:
https://dev.to/wdp

The other possibility is to leverage Next.js blog function combining it with markdown files and a library to parse those files. That would give us total control of the page stylings and every publication would be managed by Github.

https://dev.to/alexmercedcoder/2022-tutorial-on-creating-a-markdown-blog-with-nextjs-3dlm

The main drawback I foresee is that only devs would be able to post things independently... Thoughts @cherylli , @vmcodes , @klezi10 , @Denise-Carlson , @Faith-Nchifor , @ZahraB21 ?

**Comment by cherylli** [comment]
So i've tested with dev.to api a bit and it works great so far using next.js SSR/ISR.
code: https://gitlab.com/test-projects47/wdp-blog-api-test/-/blob/main/pages/devto.js
netlify: https://shimmering-travesseiro-e717d9.netlify.app/devto

search by tag will probably be directed to another page like /pages/posts/[...tag], then query the api again with tag

dev.to api docs https://developers.forem.com/api#operation/getUserArticles

@vmcodes

**Comment by vmcodes** [comment]
> So i've tested with dev.to api a bit and it works great so far using next.js SSG/ISR. code: https://gitlab.com/test-projects47/wdp-blog-api-test/-/blob/main/pages/devto.js netlify: https://shimmering-travesseiro-e717d9.netlify.app/devto
> 
> search by tag will probably be directed to another page like /pages/posts/[...tag], then query the api again with tag
> 
> dev.to api docs https://developers.forem.com/api#operation/getUserArticles
> 
> @vmcodes

@cherylli  I like this option a lot and would be completely okay with using it. I want to look into it a little more and see how the content is generated.

I would also like to mention the MDX option again, seen here: [MDX with Next.js](https://nextjs.org/docs/advanced-features/using-mdx). Depending on how the content creation is being handled, I think this could be a simple solution. I think that using MDX would allow blog posts writers to focus on writing and also simplify development by allowing by allowing us to import components into markdown essentially.

Regardless, I'm open to any options and will do more research as we narrow the list down.

**Comment by klezi10** [comment]
>The main thing that makes me prefer using a platform as dev.to for now is the fact that we can empower other tech people who are not necessarily devs to also write quite independently of us since I'd only have to invite them as team members of our organization on dev.to (https://dev.to/wdp).

I think this is a great reason to use dev.to. I originally post on hashnode but then cross-post to dev.to (they allow me to include a canonical link). Web Dev Path pulling from dev.to would make sense. It's also a very popular blogging platform and non-devs post there as well.

**Comment by Faith-Nchifor** [comment]
@mariana-caldas  If 

> > I found out hashnode api does not support teams so I looked at dev.to it seems it has all the features we wanted,
> > 
> > * oranisation,
> > * api
> > * search by tags using query parameters
> 
> Love it, @cherylli ! I've created an organization to test it. It seems I just need to invite people by giving them a code: https://dev.to/wdp
> 
> The other possibility is to leverage Next.js blog functions by combining them with markdown files and a library to parse those files. That would give us total control of the page stylings, and Github would manage every publication.
> 
> https://dev.to/alexmercedcoder/2022-tutorial-on-creating-a-markdown-blog-with-nextjs-3dlm
> 
> The main drawback I foresee is that only devs can post independently... Thoughts @cherylli , @vmcodes , @klezi10 , @Denise-Carlson , @Faith-Nchifor , @ZahraB21 ?

@mariana-caldas is it possible to use more than one CMS? For instance dev.to and Contentful. The idea is that those who are non devs can use one while devs can use the other or both.

**Comment by mariana-caldas** [comment]
> @mariana-caldas If
> 
> > > I found out hashnode api does not support teams so I looked at dev.to it seems it has all the features we wanted,
> > > 
> > > * oranisation,
> > > * api
> > > * search by tags using query parameters
> > 
> > 
> > Love it, @cherylli ! I've created an organization to test it. It seems I just need to invite people by giving them a code: https://dev.to/wdp
> > The other possibility is to leverage Next.js blog functions by combining them with markdown files and a library to parse those files. That would give us total control of the page stylings, and Github would manage every publication.
> > https://dev.to/alexmercedcoder/2022-tutorial-on-creating-a-markdown-blog-with-nextjs-3dlm
> > The main drawback I foresee is that only devs can post independently... Thoughts @cherylli , @vmcodes , @klezi10 , @Denise-Carlson , @Faith-Nchifor , @ZahraB21 ?
> 
> @mariana-caldas is it possible to use more than one CMS? For instance dev.to and Contentful. The idea is that those who are non devs can use one while devs can use the other or both.

I don't think we need two solutions here @Faith-Nchifor , we'd end up with two resources to maintain, so why?

**Comment by mariana-caldas** [comment]
Besides dev.to, I also find Strapi a good solution and I see both of you like it @vmcodes and @cherylli .

It is self-hosted and free for open-source projects -> https://strapi.io/pricing-self-hosted
It doesn't seem to be very complicated to set up with next -> https://strapi.io/blog/build-a-blog-with-next-react-js-strapi

Which one would you prefer and why team?

**Comment by cherylli** [comment]
> Besides dev.to, I also find Strapi a good solution and I see both of you like it @vmcodes and @cherylli .
> 
> It is self-hosted and free for open-source projects -> https://strapi.io/pricing-self-hosted
> It doesn't seem to be very complicated to set up with next -> https://strapi.io/blog/build-a-blog-with-next-react-js-strapi
> 
> Which one would you prefer and why team?

But this article doesn't involve user accounts right? If you are wanting to have multiple people blogging. We could implement it ourselves but significantly more effort than using existing platforms.

Also how do people write the article? Do we have to implement an interface or is there one built in? 

I've only used strapi once, so I don't know much about it.

Both sound interesting to implement.

If I was the person writing an article, I probably prefer dev.to or hashnode because of the exposure. 

Depends on the time frame, like how quickly you want it to be implemented, we could also use Dev.to API to start with and slowly migrate it to strapi if that's what you want. It takes little effort to implement it and if we do a styling main page and single post they could also be reused

**Comment by cherylli** [comment]
So I think it might be like wordpress you can create accounts for people on strapi and they can edit like this

https://docs.strapi.io/assets/img/qsg-handson-part2-03-restaurant.a35be858.png

**Comment by mariana-caldas** [comment]
> > Besides dev.to, I also find Strapi a good solution and I see both of you like it @vmcodes and @cherylli .
> > It is self-hosted and free for open-source projects -> https://strapi.io/pricing-self-hosted
> > It doesn't seem to be very complicated to set up with next -> https://strapi.io/blog/build-a-blog-with-next-react-js-strapi
> > Which one would you prefer and why team?
> 
> But this article doesn't involve user accounts right? If you are wanting to have multiple people blogging. We could implement it ourselves but significantly more effort than using existing platforms.
> 
> Also how do people write the article? Do we have to implement an interface or is there one built in?
> 
> I've only used strapi once, so I don't know much about it.
> 
> Both sound interesting to implement.
> 
> If I was the person writing an article, I probably prefer dev.to or hashnode because of the exposure.
> 
> Depends on the time frame, like how quickly you want it to be implemented, we could also use Dev.to API to start with and slowly migrate it to strapi if that's what you want. It takes little effort to implement it and if we do a styling main page and single post they could also be reused (Edit: actually probably doesn't matter as we don't already have any written articles anyway)

Yep, the account creation is like you mention below, @cherylli 
In terms of time frame, it would be great to have the blog working by Jan 2023, but I think it's more important to find a robust solution we all like and we can learn from it than finish it fast. However, you highlight something I haven't considered before, Cheryl, which is the exposure the authors would have if we decide to go with dev.to. 
Are you both OK, @vmcodes and @cherylli , if we give dev.to a try?

**Comment by cherylli** [comment]
i'm ok with whichever you decide

**Comment by mariana-caldas** [comment]
Let us give dev.to a try!
I'm creating the first issue this weekend by considering our Slack conversations, @cherylli 🙌🏼 
Thanks so much, team, for the insights! 🙇🏼‍♀️ 
Closing this issue for now 🎉
